@host= http://localhost:5175

POST {{host}}/auth/register
Content-Type: application/json

{
    "FirstName": "Happy",
    "LastName": "Day",
    "Email": "iamregistered@gmail.com",
    "Password": "Congrats123",
}