@host= http://localhost:5175

POST {{host}}/auth/register
Content-Type: application/json

{
    "FirstName": "Happy",
    "LastName": "learning",
    "Email": "Iamregistered@gmail.com",
    "Password": "Learning"
}